# Generated by Django 3.2.16 on 2023-09-21 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_inboundsms_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='informant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='informant_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='operation_type',
            field=models.CharField(blank=True, choices=[('search', 'Search'), ('rescue', 'Rescue')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='radio_channel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='resolution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('resolved', 'Resolved'), ('archived', 'Archived')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='subject_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='informant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='informant_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='operation_type',
            field=models.CharField(blank=True, choices=[('search', 'Search'), ('rescue', 'Rescue')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='radio_channel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='resolution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('resolved', 'Resolved'), ('archived', 'Archived')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='subject_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='finish_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='finish_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='start_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='CalloutResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response', models.CharField(max_length=255)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.period')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CalloutLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('lat', models.CharField(blank=True, max_length=255, null=True)),
                ('lon', models.CharField(blank=True, max_length=255, null=True)),
                ('update', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
