# Generated by Django 3.2.16 on 2023-10-10 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_callout_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcalloutresponse',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical callout response', 'verbose_name_plural': 'historical callout responses'},
        ),
        migrations.AlterModelOptions(
            name='historicalevent',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical event', 'verbose_name_plural': 'historical events'},
        ),
        migrations.AlterModelOptions(
            name='historicalmember',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical member', 'verbose_name_plural': 'historical members'},
        ),
        migrations.AlterModelOptions(
            name='historicalparticipant',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical participant', 'verbose_name_plural': 'historical participants'},
        ),
        migrations.AlterModelOptions(
            name='historicalperiod',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical period', 'verbose_name_plural': 'historical periods'},
        ),
        migrations.AlterModelOptions(
            name='historicalrole',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical role', 'verbose_name_plural': 'historical roles'},
        ),
        migrations.AlterField(
            model_name='historicalcalloutresponse',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmember',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalparticipant',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalperiod',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalrole',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
