# Generated by Django 3.2.16 on 2023-10-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20231014_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='operation_type',
            field=models.CharField(blank=True, choices=[('search', 'Search'), ('rescue', 'Rescue'), ('information', 'Information')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='operation_type',
            field=models.CharField(blank=True, choices=[('search', 'Search'), ('rescue', 'Rescue'), ('information', 'Information')], max_length=255, null=True),
        ),
    ]
