# Generated by Django 3.2.16 on 2023-10-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20231015_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='finish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='notifications_made',
            field=models.ManyToManyField(blank=True, to='main.EventNotificationsAvailable'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='finish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
