# Generated by Django 3.2.16 on 2023-11-02 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20231030_1715'),
        ('main', '0023_auto_20231015_2135'),
    ]

    operations = [
    ]
