# Generated by Django 3.2.16 on 2023-11-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_calloutresponseoption'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='patrol',
            constraint=models.UniqueConstraint(fields=('member', 'date'), name='unique_patrol'),
        ),
    ]
