# Generated by Django 3.2.16 on 2023-11-11 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_patrol_unique_patrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calloutlog',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.event'),
        ),
    ]
