# Generated by Django 3.2.16 on 2024-05-07 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_calloutlog_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioChannelsAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.IntegerField(default=1, null=True)),
                ('name', models.CharField(max_length=255)),
                ('is_primary', models.BooleanField(default=True)),
                ('is_additional', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['position'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='calloutlog',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='additional_radio_channels',
            field=models.ManyToManyField(blank=True, to='main.RadioChannelsAvailable'),
        ),
    ]
