# Generated by Django 4.2.6 on 2024-09-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_calloutresponse_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberstatustype',
            name='color',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
