# Generated by Django 4.2.6 on 2024-10-05 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_cert'),
        ('main', '0033_patrol'),
    ]

    operations = [
    ]
