# Generated by Django 4.2.6 on 2024-11-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_merge_0017_cert_0033_patrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='published',
            field=models.BooleanField(default=False, help_text='Published events are viewable on the public and private calendar.'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='published',
            field=models.BooleanField(default=False, help_text='Published events are viewable on the public and private calendar.'),
        ),
    ]
