# Generated by Django 4.2.6 on 2024-11-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_event_published_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberstatustype',
            name='is_patrol_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberstatustype',
            name='is_patrol_expected',
            field=models.BooleanField(default=False),
        ),
    ]
