# Generated by Django 4.2.6 on 2024-11-21 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_memberstatustype_is_patrol_eligible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='format',
            field=models.CharField(choices=[('page', 'Page'), ('password_reset', 'Password reset'), ('cert_notice', 'Cert notice'), ('do_shift_starting', 'DO Shift Starting'), ('do_shift_pending', 'DO Shift Pending'), ('patrol_reminder', 'Patrol reminder')], max_length=255),
        ),
    ]
