# Generated by Django 4.2.6 on 2024-11-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_message_author_and_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='format',
            field=models.CharField(choices=[('page', 'Page'), ('password_reset', 'Password reset'), ('cert_notice', 'Cert notice'), ('do_shift_starting', 'DO Shift Starting'), ('do_shift_pending', 'DO Shift Pending'), ('patrol_reminder', 'Patrol reminder'), ('patrol_summary', 'Patrol summary')], max_length=255),
        ),
    ]
