# Generated by Django 4.2.6 on 2024-12-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_message_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert',
            name='type',
            field=models.CharField(blank=True, choices=[], max_length=255, null=True),
        ),
    ]
