# Generated by Django 4.2.6 on 2024-12-29 07:24

from django.db import migrations

def fill_event_operation_type_fk(apps, schema_editor):
  Event = apps.get_model('main', 'Event')
  OperationTypesAvailable = apps.get_model('main', 'OperationTypesAvailable')
  for event in Event.objects.all():
    if event.operation_type:
      event.operation_type_fk, created = OperationTypesAvailable.objects.get_or_create(name=event.operation_type, icon='')
      event.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_operationtypesavailable_event_operation_type_fk_and_more'),
    ]

    operations = [
        migrations.RunPython(fill_event_operation_type_fk),
    ]
