# Generated by Django 4.2.6 on 2024-12-30 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_operation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='operation_type',
        ),
        migrations.RemoveField(
            model_name='historicalevent',
            name='operation_type',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='operation_type_fk',
            new_name='operation_type',
        ),
        migrations.RenameField(
            model_name='historicalevent',
            old_name='operation_type_fk',
            new_name='operation_type',
        ),
    ]
