# Generated by Django 4.2.6 on 2025-01-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_remove_event_operation_type_fk_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calloutresponseoption',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='calloutresponseoption',
            name='color',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='calloutresponseoption',
            name='position',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
