# Generated by Django 4.2.6 on 2026-07-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_remoteserver_remoteserverapikey_remotemapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiochannelsavailable',
            name='is_additional',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='radiochannelsavailable',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
